---
title: "Reference"
output: 
    html_document:
        toc: true
        theme: united
---

```{r setup, echo=FALSE, include=FALSE}

```

## Console Navigation

#### Show current directory
`pwd`

#### List files
`ls`  
`ls -l` (cleaner format, shows permissions)  
`ls -a` (show hidden)  

#### Go to directory
`cd`  
`cd [path]` (specific directory e.g. cd /srv/shiny-server)  
`cd ..` (up one)  

#### View file
`less` (up/down arrow keys and page up/down, q to quit)  

#### Create file/dir
`touch [file]`  
`mkdir [path]`  

#### Move files
`mv` (e.g. mv file directory)  

#### Rename files
`mv [file name] [new file name]` (be careful as this will overwrite)  

#### Copy file
`cp [file] [dir]`  

#### Copy directory
`cp -r [dir] [dir]` (-r makes it recursive to move the whole directory)  

#### Delete file/dir
`rm [file]`  
`rmdir [dir]`  

#### Edit files
`nano [file]` (open file, opens interface, shows controls as "^[key]" which means CTRL+[key])  
`CTRL-G` shows help  
`CTRL-X` goes back/quits  
`CTRL-O` saves  

### Permissions

#### Notation
`drwxrwxrwx`, `drwxr--r--`  
`d`: filetype  
`rwx`: user (owner)  
`rwx`: group   
`rwx`: other  
(read, write, execute)  

#### Octals
4: read  
2: write  
1: execute  
Add together for each category (user, group, other)  
e.g. 777 = full permission  

#### Change permissions using octal notation
`chmod 777 [path]` (use . to reference all)  


## Console General

#### Updating
`sudo apt update`  
`sudo apt -y upgrade` - `-y` replies with yes to prompts automatically  
`sudo service nginx restart`  

#### Memory

The Shiny Server needs swap memory to handle all the R packages used and the data used for apps. Swap memory is created by making a file that sits in the server and it basically sets hard drive space aside to supplement RAM.  

`sudo fallocate -l 4G /swapfile4G`
`sudo mkswap /swapfile4G`
`sudo swapon /swapfile4G`
`sudo swapoff /swapfile # < old swapfile` (to replace an old swap file if it needs to be resized)
`sudo rm /swapfile`
`sudo swapon -s # verify `

The default upload size limit for client is ~1mb. To change this, `client_max_body_size 1000M;` can be added to `/etc/nginx/nginx.conf` in the `http` block.


## Shiny Server

#### Restart Shiny Server (or start/stop by replacing 'restart')
`sudo systemctl restart shiny-server`  

#### Install packages for the server
`sudo su - -c "R -e \"install.packages('devtools', repos='http://cran.rstudio.com/')\""` (CRAN)  
`sudo su - -c "R -e \"devtools::install_github('daattali/shinyjs')\""` (GitHub)  

#### Installed packages  
 - `sudo su - -c "R -e \"install.packages('devtools', repos='http://cran.rstudio.com/')\""`  
 - `sudo su - -c "R -e \"install.packages('shiny', repos='http://cran.rstudio.com/')\""`   
 - `sudo su - -c "R -e \"install.packages('shinyjs', repos='http://cran.rstudio.com/')\""`   
 - `sudo su - -c "R -e \"install.packages('tidyverse', repos='http://cran.rstudio.com/')\""`   
 - `sudo su - -c "R -e \"install.packages('lubridate', repos='http://cran.rstudio.com/')\""`   
 - `sudo su - -c "R -e \"install.packages('RSQLite', repos='http://cran.rstudio.com/')\""`   
 - `sudo su - -c "R -e \"install.packages('DBI', repos='http://cran.rstudio.com/')\""`   
 - `sudo su - -c "R -e \"install.packages('jsonlite', repos='http://cran.rstudio.com/')\""`  
 - `sudo su - -c "R -e \"devtools::install_github('rstudio/reticulate')\""`  
 - `sudo su - -c "R -e \"install.packages('DT', repos='http://cran.rstudio.com/')\""`  
 - `sudo su - -c "R -e \"install.packages('plotly', repos='http://cran.rstudio.com/')\""`  
 - `sudo su - -c "R -e \"install.packages('ggridges', repos='http://cran.rstudio.com/')\""`  
 - `sudo su - -c "R -e \"install.packages('quantmod', repos='http://cran.rstudio.com/')\""`
 
 
 
## RStudio Server

#### Restart RStudio Server 
`sudo rstudio-server restart` 

### Kill RStudio sessions  
If a session gets stuck for whatever reason (often printing an object that is too large) you can just kill all the sessions. RStudio settings might change as a result.  
`sudo rstudio-server kill-all`  
  

## Git

You need to be in the directory that corresponds to the repo for this to work.  

### Flows
Working directory > Staging > Local repo > Remote repo (master)
`git add` > `git commit` > `git push`  

Working directory < Remote repo (master)
`git pull`  

#### Stage all files
`git add .`  

#### Stage specific file
`git add [filepath]`  

#### See staged files
`git status`  

#### Commit to repo
`git commit -m "commit message/description"`  

#### Uncommit
`git reset HEAD~1`  

#### Set up remote repo
`git remote add origin [repo url/GitHub repo link]`  

#### Push changes to remote repo
`git push -u origin master`  

#### See changes
`git diff`  

#### See history
`git log`  

#### Roll back to last committed version (replace . with filepath for specific file)
`git checkout .`  

#### Get most recent version of repo
`git pull origin master`  

### Typical flow
`git add .`  
`git status`  
`git commit -m "message"`  
`git push -u origin master`  


## Python

Python comes with Ubuntu  
`python3 -V`

#### Installing pip
`sudo apt install -y python3-pip`  

#### Installing packages
`pip3 install [package]`

### Anaconda  

#### Environments

#####`d2`
`conda install --name d2 requests`  
`conda install --name d2 Pillow`





